### ISSUE TITLE
Permitir acrescentar informações de "Apresentação da Proposta" nos Cards de acordo com uma permissão para o PCom

### ISSUE THREAD

**Issue by vlribeiro** [Saphyr-SC/issues-tc#101]
Na tela antiga de Aprovar Proposta, vamos permitir que o usuário possa acrescentar informação no campo Aprsentação da Proposta/Negociação, como no print abaixo:

![image](https://user-images.githubusercontent.com/1081010/218534466-e953484b-3731-4873-be1c-288b0b17fc41.png)

A ideia geral é criar um botão "Editar Apresentação" nessa célula, que ficará visível apenas para usuários que tenham uma nova permissão que iremos criar.
Ao clicar nesse botão, o sistema abre uma modal com uma caixa de texto para que seja possível inserir e/ou editar a informação do campo `historiconegociacao` da entidade `Proposta`.
A edição do campo não acarreta no retorno da proposta para ser aprovada novamente (não podemos utilizar o método de edição de proposta que já existe hoje, devemos criar um específico).

## Principais tarefas

- [x] Criar uma nova permissão `ComplementarInformacoesProposta` (ou algo do tipo) que será utilizada para definir se o botão deve aparecer ou não
- [x] Criar um botão em baixo do texto "Apresentação da Proposta/Negociação" na tela antiga de aprovação de propostas, esse botão só pode estar visível para usuários que possuam a permissão criada no item anterior
- [x] Ao clicar no botão, exibir uma modal onde será possível inserir ou editar a informação do campo `historiconegociacao` da Proposta que está sendo exibida na tela
- [x] Ao salvar as alterações na modal, recarregar a tela com a nova informação

**Comment by v1n1Fernand0** [comment]
Oi, vini blz? Poderia dar uma detalhada nessa tarefa para mim? Eu lembra de vermos a antiga da proposta, mas o titulo me deixou um pouco confuso sobre onde realizar a tarefa.

**Comment by v1n1Fernand0** [comment]
Perfeito! Muito obrigado :)
