### ISSUE TITLE
Ao selecionar uma área inferior a 100% da LUC, não está sendo possível mudar o EV da negociação

### ISSUE THREAD

**Issue by vlribeiro** [Saphyr-SC/issues-tc#113]
Bug reportado por EV e validado pelo Julio e Giovani

**Comment by v1n1Fernand0** [comment]
Não consegui replicar o erro! Vou entrar em contato com o pessoal que reportou para verificar melhor.
![image](https://user-images.githubusercontent.com/71952518/221596034-7e91bb7e-6f57-4a75-84ea-4c235f8f1045.png)
![image](https://user-images.githubusercontent.com/71952518/221596277-55a2c09a-51c7-41b7-928d-0711dd06e813.png)
