### ISSUE TITLE
Extração de Propostas Declinadas do SMT - Thaís França

### ISSUE THREAD

**Issue by vlribeiro** [Saphyr-SC/issues-tc#120]
Extrair dados de Propostas declinadas do SMT.

Filtros utilizados:

- Data de Corte: 01/01/2019 a 01/03/2023
- Shopping: SMT
- Status: Desistência (id 11)

# Output de Saída:

Um Excel com os dados, com a seguinte estrutura:

| Responsável | # Proposta | Marca | Contato | LUC | ABL | Data de Declínio |
| - | - | - | - | - | - | - |
| *ev responsável pela proposta* | *id da proposta, se possível acho que pode até colocar um link pra proposta no sistema* | | *propostas antigas podem não ter contato* | *concatenar todas as LUCs em uma linha só* | *somar a área utilizada de todas as LUC. tabela `PropostaUnidade`* | *data do status de desistência ativo* |

----

Ao final, mantém a query salva que pode ser que ela peça pra fazer ajustes na saída, incluir mais campos, etc...

**Comment by v1n1Fernand0** [comment]
[queryThais.zip](https://github.com/Saphyr-SC/issues-tc/files/10874826/queryThais.zip)

**Comment by v1n1Fernand0** [comment]
Link da query 

https://saphyr1.sharepoint.com/:u:/r/sites/Labs/Documentos%20Compartilhados/Cittera%20Comercial/Queries%20%C3%9Ateis/[PropostasDeclinadasApartirDe-SMT.sql](https://saphyr1.sharepoint.com/:u:/r/sites/Labs/Documentos%20Compartilhados/Cittera%20Comercial/Queries%20%C3%9Ateis/PropostasDeclinadasApartirDe-SMT.sql?csf=1&web=1&e=9apGTA)?csf=1&web=1&e=9apGTA
