### ISSUE TITLE
E-mails de Aprovação e Reprovação de Análise de Crédito para o Responsável da Negociação

### ISSUE THREAD

**Issue by vlribeiro** [Saphyr-SC/issues-tc#139]

**Comment by thiagodesantos** [comment]
@vlribeiro 
Já tem os emails de analise reprovada , aprovada e aprovada não recomendada

**Comment by vlribeiro** [comment]
Boa, @thiagodesantos , consegue fazer um teste em dev enviando um exemplo desses emails pra gente? só pra gente usar na próxima reunião com o Giovani e validar os modelos.
