### ISSUE TITLE
Previsão de inauguração passar a ser obrigaória ao transformar negociação em proposta

### ISSUE THREAD

**Issue by vlribeiro** [Saphyr-SC/issues-tc#156]

**Comment by thiagodesantos** [comment]
@vlribeiro 


![Image](https://user-images.githubusercontent.com/39632450/235990947-fa8bb0c0-1bb0-43e7-ab7c-dde6d4e8082a.png)

já esta feito, não entendi porque solicitaram novamente

**Comment by vlribeiro** [comment]
@thiagodesantos, será que não pode estar tendo algum caso que conseguiram transformar sem preencher? ou casos de propostas antigas?
Vamos perguntar pro Giovani amanhã um exemplo de proposta que esteja sem a info 😉
