### ISSUE TITLE
Validação do quadro de Analise comparativa de propostas

### ISSUE THREAD

**Issue by thiagodesantos** [Saphyr-SC/issues-tc#160]

**Comment by thiagodesantos** [comment]
@vlribeiro ,
pra fechar essa issue aew só preciso saber se é correto fazer a media com base em um valor zerado,
vamos dizer que tivemos 5 boleto mas desses 5 boletos só 4 tiveram valor, divido esse valor por 4 ou por 5?

**Comment by vlribeiro** [comment]
@thiagodesantos acho que depende de qual rubrica vc tá falando...

Por exemplo, pra desconto isso não faz sentido... Pra condomínio, aluguel, acho que faz.

**Comment by thiagodesantos** [comment]
> @thiagodesantos acho que depende de qual rubrica vc tá falando...
> 
> Por exemplo, pra desconto isso não faz sentido... Pra condomínio, aluguel, acho que faz.

mas faz sentido oque, dividir por 4 ou 5 no aluguel e condomínio

**Comment by vlribeiro** [comment]
> mas faz sentido oque?, dividir por 4 ou 5 no aluguel e condomínio

então, se o cara teve um mês que o aluguel foi 0, faz sentido que aquilo seja considerado na divisão...

6 meses de aluguel:

| Mês 1 | Mês 2 | Mês 3 | Mês 4 | Mês 5 | Mês 6
|-|-|-|-|-|-|
| 1000 | 1000 | 1000 | 0 | 1000 | 1000 |

A média ficaria como em

```math
{\left(1000 + 1000 + 1000 + 0 + 1000 + 1000 \right) \over 6} = 833.33
```

Pro caso de desconto eu vejo que isso não deve fazer sentido (como a gente já fez antes) que o 0 significa que o desconto não existiu naquele mês, então não consideraria na média.

Faz sentido?

De qualquer forma, pode tentar ver com o Giovani o que ele entende que seria melhor pra cada caso e colocar a resposta dele aqui pra gente discutir, se achar melhor.

**Comment by thiagodesantos** [comment]
@vlribeiro 
então ta tudo certo, vou fechar a issue
ja ta publicado , aew fica pro giovani conferir tudo depois quando a gente mostrar oque foi feito no sprint
