### ISSUE TITLE
Renovações - Alteração no calculo de VGLC

### ISSUE THREAD

**Issue by thiagodesantos** [Saphyr-SC/issues-tc#163]
Karina  : 
O VGLC do contrato atual, pode ser calculado pegando o valor do AMM atual e condomínio atual que já temos em telas anteriores e nesta mesma tela.

**Comment by thiagodesantos** [comment]
@vlribeiro 
duvida eternas de calculos,
como calculo o VGLC quando não tenho o condomínio em especifico , só algumas coisas dele, exemplo :  


![Image](https://github.com/Saphyr-SC/issues-tc/assets/39632450/e6a60313-3c68-4c03-bcaa-526ac011ac00)

**Comment by thiagodesantos** [comment]
Seria , amm * qtd total de meses + encargo comum * prazo ?

**Comment by vlribeiro** [comment]
@thiagodesantos 

Nesse caso do exemplo, acredito que você vai levar em conta os dados que você tem que compões o VGLC.

Sempre lembrando que VGLC = VGL + VGC
VGL = Aluguel + CDU
VGC = Condomínio

Se qualquer uma dessas informações não existir, você vei colocar 0 no lugar... Exemplo: se o contrato não tem condomínio, o VGC é 0. Não tem Aluguel, o VGL é só CDU.

No teu caso que é renovação, CDU já não existe de cara... então teu VGL é só Aluguel sempre.

Com a tabela do exemplo que você anexou, eu entendo que as únicas linhas que importem pro cálculo do VGLC são a "AMM Contratual" e a "Encargo Comum".

Acho que é isso.

**Comment by thiagodesantos** [comment]
@vlribeiro 
~seria assim então ? 


![Image](https://github.com/Saphyr-SC/issues-tc/assets/39632450/05e847a9-ee68-4f5e-9438-6b4b4298aece)

**Comment by vlribeiro** [comment]
> Seria , amm * qtd total de meses + encargo comum * prazo ?

@thiagodesantos isso aí, só parece que esses valores são por m² pelo que tô vendo, aí teria que multiplicar pela área tbm... Mas é basicamente isso.

**Comment by vlribeiro** [comment]
> @vlribeiro ~seria assim então ?
> 
> ![Image](https://user-images.githubusercontent.com/39632450/239382365-05e847a9-ee68-4f5e-9438-6b4b4298aece.png)

Então... eu acho esse cálculo simplório...

**Toda** negociação de renovação vai ter 13 aluguéis? **Toda** negociação de renovação vai ser por 60 meses?

Pra mim o correto é:

((Aluguel * (Prazo - Carência de Aluguel)) + Total de Incrementais) + (Condomínio * (Prazo - Carência de Condomínio)) - Desconto Contratual

Mas se eles quiserem que fique fixo esse "65" e "60", eu acho que vai deixar o sistema muito pobre... nunca vai poder ser negociada uma renovação de 10 anos? ou uma renovação que não tenha incremental? Sei lá, não acho que faz sentido fazer assim. Prefiro fazer a conta com os atributos da Entidade Proposta ao invés de com números fixos.

**Comment by vlribeiro** [comment]
@thiagodesantos você não tá usando a entidade `Proposta` pra representar uma renovação? Ela já tem o cálculo de VGLC, se os atributos estiverem preenchidos certinhos... Não tá batendo com o que eles acham que deveria ser? Não vejo porque desenvolver esse algoritmo de novo...

**Comment by thiagodesantos** [comment]
> @thiagodesantos você não tá usando a entidade `Proposta` pra representar uma renovação? Ela já tem o cálculo de VGLC, se os atributos estiverem preenchidos certinhos... Não tá batendo com o que eles acham que deveria ser? Não vejo porque desenvolver esse algoritmo de novo...

é na inserção , eu apresento um quadro q simula os possíveis valores

**Comment by vlribeiro** [comment]
@thiagodesantos entendi.

A gente pode pensar em montar no JS uns helpers, uma função que você passe todos os parâmetros certinhos e ela faça o cálculo pra usar em vários lugares com um cálculo só.

O que acha? Posso criar uma issue aqui pra montar um helper js de cálculo de VGLC e vc ser minha primeira cobaia, depois vamos colocando nos outros lugares do sistema com calma...

**Comment by thiagodesantos** [comment]
> @thiagodesantos entendi.
> 
> A gente pode pensar em montar no JS uns helpers, uma função que você passe todos os parâmetros certinhos e ela faça o cálculo pra usar em vários lugares com um cálculo só.
> 
> O que acha? Posso criar uma issue aqui pra montar um helper js de cálculo de VGLC e vc ser minha primeira cobaia, depois vamos colocando nos outros lugares do sistema com calma...

Acho maneiro a ideia mas eu to com um sentimento de terminar isso logo q fico pensando kkkkk, só quero q a dor pare
