### ISSUE TITLE
Puxar valores da Tabela Comparativa a partir do Cittera Financeiro

### ISSUE THREAD

**Issue by vlribeiro** [Saphyr-SC/issues-tc#28]
Hoje, puxamos os valores da Tabela Compartiva de Propostas levando em consideração o valor contratual dentro do Cittera Comercial.

Precisamos passar a puxar valores do Cittera Financeiro, de acordo com alguma regra definida pelo time de Negócios.

**Comment by tsantosSaphyr** [comment]
@vlribeiro 
acho que faltou a gente definir melhor um pouco como vão ser trazidos esses valores,
a renovação vai media dos últimos boletos, se não formos fazer assim vamos precisar ver alguns ajustes na api do financeiro

**Comment by vlribeiro** [comment]
@thiagodesantos sim, eu sei, por isso que coloquei na descrição _"de acordo com alguma regra definida pelo time de Negócios"_ e marquei com a tag https://github.com/Saphyr-SC/issues-tc/labels/question, tudo que estiver com essa tag vou indicar pro Julio que precisamos de definição.

Abri as issues pra organizar e ter no quadro, mas não significa que tudo tá pronto pra ser implementado já 😁

**Comment by vlribeiro** [comment]
@thiagodesantos repara tbm que não tá dentro dessa sprint, então ainda não tá planejado pra gente fazer ainda 🤟

**Comment by vlribeiro** [comment]
@thiagodesantos e @v1n1Fernand0 , temos as definições de como vamos puxar os valores do Financeiro:

Definição do Giovani e Julio:

> Vamos pegar o seguinte recorte para comparar com as propostas: 6 meses de faturamento só que sem considerar dezembro.
> Em casos de desconto (se conseguirmos mapear isso de acordo com as infos do cittera financeiro) desconsiderar também o mês que tiver mais de 50% de desconto do AMM

**Comment by thiagodesantos** [comment]
durante o processo de desenvolvimento tivemos a seguinte duvida:
exemplo: desconto medio
notamos que nem sempre tem desconto nos meses 


![Image](https://user-images.githubusercontent.com/39632450/229227966-73e607cb-a528-4c24-9096-662c792321a3.png)


no caso a divisão seria pelos 6 meses? ou só vamos dividir pela quantidade de meses que tiveram o desconto, no exemplo a cima seria dividido por 2 por só 2 meses tiveram desconto.

**Comment by vlribeiro** [comment]
Já está disponível em produção.
