### ISSUE TITLE
Remover Shoppings inativos e de outros Grupos da Tabela Comparativa da Proposta

### ISSUE THREAD

**Issue by vlribeiro** [Saphyr-SC/issues-tc#44]

**Comment by vlribeiro** [comment]
@thiagodesantos , eu não tenho certeza se você já fez esse item. De qualquer forma abri, a partir do nosso Excel de melhorias junto ao Julio.
Se já estiver finalizado, pode fechar, por favor.

**Comment by tsantosSaphyr** [comment]
@vlribeiro ,
to muito na duvida, ja olhei em prod os casos, eu sei que fiz um ajuste há um tempo, vou ate colocar aqui query que ele usa pra trazer la os dados, acho que já ta concluído mas vou deixar em aberto pra acompanhar , em prod não encontrei nenhum caso 

https://github.com/Saphyr-SC/Comercial/blob/4250214186eb7eb816a28b70a54afb7d13cc18b7/ApoioComercializacao/ApoioComercializacao.Web/Queries.xml#L4029-L4053

**Comment by vlribeiro** [comment]
Deve estar funcionando corretamente, vamos ficar de olho se o erro ocorre novamente.
