### ISSUE TITLE
Cálculo do Condomínio na Tabela Comparativa

### ISSUE THREAD

**Issue by vlribeiro** [Saphyr-SC/issues-tc#55]
Replicar calculo da proposta, sem levar em conta a alteração que o EV fez

**Comment by tsantosSaphyr** [comment]
@vlribeiro , poderia descrever um pouco mais ?

**Comment by vlribeiro** [comment]
@thiagodesantos acredito que é pra levarmos em conta o cálculo do CRD e/ou condmínio fixo, de acordo com o que foi preenchido pelo EV.

- EV escolheu condomínio Fixo/m²: é só respeitar o valor de condomínio que ele preencheu e exibir na tabela
- EV escolheu condomínio CRD: respeitar o cálculo de Valor de Condomínio já implementado (considerando fatores e CRD) para exibir o valor de condomínio/m² na tabela
