### ISSUE TITLE
Ajustar Tabela Comparativa para usar Aluguel Médio das Propostas nas colunas que não forem Tabela (verde) e Aluguel do Primeiro Ano na coluna Tabela (verde)

### ISSUE THREAD

**Issue by vlribeiro** [Saphyr-SC/issues-tc#75]
- Ajustar a linha que hoje exibe AMM/m² médio para exibir AMM/m² do primeiro ano
- Ajustar cálculo do FPP para levar em consideração apenas o primeiro ano de tabela

**Comment by v1n1Fernand0** [comment]
A parte do FPP já estava pegando certo!

**Comment by vlribeiro** [comment]
Passar a utilizar a média de aluguéis em todas as coluna que não forem a coluna verde "Tabela"
