### ISSUE TITLE
Incluir informação de A% no Quadro Comparativo de Propostas

### ISSUE THREAD

**Issue by vlribeiro** [Saphyr-SC/issues-tc#85]
Precisamos incluir uma nova linha na Tabela Comparativa de Propostas abertas no Quadro de Pipeline, com a informação de Aluguel Percentual.

Título da linha: A%
Trazer o valor de Aluguel Percentual de cada proposta carregada na tabela, além de Orçamento e previsão de Tabela.

![Image](https://user-images.githubusercontent.com/1081010/221870290-0bce513c-5dc8-40fb-8206-a1b3bfdb692f.png)

**Comment by v1n1Fernand0** [comment]
Consegui finalizar a tarefa, porém estou usando a propriedade "aluguelpercentual". Ficamos de validar o if na propriedade "AluguelPercentualNovo", referenciada no link abaixo.
 
https://github.com/Saphyr-SC/Comercial/blob/7135c83818e135f76581e40354c97375ca31aa70/ApoioComercializacao/ApoioComercializacao.Entities/Proposta.cs#L1103

**Comment by vlribeiro** [comment]
Finalizado pelo @v1n1Fernand0
